/**
 * Supabase Database Types
 *
 * PLACEHOLDER — This file will be replaced automatically after Step 3.
 *
 * Once your Supabase project is created and migrations are run (Step 5),
 * regenerate this file with:
 *
 *   pnpm supabase gen types typescript \
 *     --project-id YOUR_PROJECT_ID \
 *     > packages/types/src/database.ts
 *
 * Or with the local Supabase CLI:
 *   pnpm supabase gen types typescript --local \
 *     > packages/types/src/database.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// ─────────────────────────────────────────────────────────────────────────────
// Place types — matches places.place_type column (v2.1 schema)
// ─────────────────────────────────────────────────────────────────────────────
export type PlaceType =
  | 'business'
  | 'restaurant'
  | 'beach'
  | 'trail'
  | 'park'
  | 'attraction'
  | 'organization'
  | 'nature_spot'
  | 'real_estate'

export type PlaceStatus = 'pending' | 'active' | 'rejected' | 'suspended'

export type PlanType = 'free' | 'starter' | 'pro' | 'enterprise'

export type UserRole =
  | 'user'
  | 'business_owner'
  | 'editor'
  | 'moderator'
  | 'admin'
  | 'super_admin'

export type Locale = 'es' | 'en'

// ─────────────────────────────────────────────────────────────────────────────
// Database interface — will be fully generated by Supabase CLI
// ─────────────────────────────────────────────────────────────────────────────
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          avatar_url: string | null
          bio: string | null
          phone: string | null
          preferred_lang: Locale
          role: UserRole
          is_banned: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name: string
          avatar_url?: string | null
          bio?: string | null
          phone?: string | null
          preferred_lang?: Locale
          role?: UserRole
          is_banned?: boolean
        }
        Update: {
          display_name?: string
          avatar_url?: string | null
          bio?: string | null
          phone?: string | null
          preferred_lang?: Locale
          role?: UserRole
          is_banned?: boolean
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      place_type: PlaceType
      place_status: PlaceStatus
      plan_type: PlanType
      user_role: UserRole
    }
  }
}
